language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - vendor/bundle
env:
  matrix:
    - JEKYLL_VERSION="~> 3.4"
    - JEKYLL_VERSION="<= 3.2"
rvm:
  - &ruby24 2.4
  - &ruby23 2.3
  - &ruby22 2.2
  - &ruby21 2.1
  - &jruby jruby-9.1.2.0
  - &rhead ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: *jruby
    - rvm: *rhead
notifications:
  email:
    recipients:
      - jordon@envygeeks.io
branches:
  only:
    - master
    - sprockets-4.x
addons:
  code_climate:
    repo_token:
      secure: "\
        SprHjZdYxOWHXrnDLKu+tTLI/28dgNlHGH9pUF0NIouu5nhWVizoRt1xK19s+6Rct9h/b8\
        H9In1ExFom05IcXX4c1JGX1LlGbWRV/BHRwgys+MpWJCLfs8kBigufDdZBmyXubEj2KsjE\
        WICu+GMg+ZHP0nVTa/FkoF5iAfY6NiE=\
      "
after_success:
  - bundle exec codeclimate-test-reporter
